### ISSUE TITLE
[BUG] policy.py에서 원하는 요소로 크롤링이 되지 않습니다.

### ISSUE THREAD

**Issue by ghost** [Wisdom-Kim/SIAT_python_crawling#2]
**## selenium - XPath로 원하는 요소 크롤링 하는 법**

content

### 설명
>
스크래핑 할 클래스의 값이 랜덤 한 값인 것 같아서 어떻게  크롤링 할지 찾다가 셀레니움의 XPath 의 기능을 알게 되었고, 코드에 적용하였습니다. 어떻게 코드를 작성해야 하는지 몰라 검색 중에 있습니다.

#### 참고 자료 (선택사항)
[[참고할 자료가 있을 경우, 기재 (커밋, 다른 이슈 멘션 등)]
https://velog.io/@ssongji/%EC%9B%B9-%ED%81%AC%EB%A1%A4%EB%A7%81-3.-selenium%EC%9D%84-%EC%9D%B4%EC%9A%A9%ED%95%B4-%EB%8F%99%EC%A0%81%EC%9D%B8-%ED%8E%98%EC%9D%B4%EC%A7%80%EC%9D%98-XPath%EB%A1%9C-%EC%9B%90%ED%95%98%EB%8A%94-%EC%9A%94%EC%86%8C-%EC%8A%A4%ED%81%AC%EB%9E%98%ED%95%91

**Comment by Wisdom-Kim** [comment]
페이지 구조를 확인해보니 class="editor-text"에서 상세페이지 내 텍스트를 가져올 수 있는 걸로 보입니다.
raw_text = find_element(By.CLASS_NAME,'editor-text').text
식으로 클래스 네임으로 가져온 후 raw_text를 전처리하면 될 것 같아요~
